"""Your migration message here

Revision ID: 7262db625bb1
Revises: 
Create Date: 2024-11-06 12:01:16.153624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7262db625bb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mid1', sa.Float(), nullable=False),
    sa.Column('mid2', sa.Float(), nullable=False),
    sa.Column('mid_avg', sa.Float(), nullable=False),
    sa.Column('semester', sa.Float(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Students')
    # ### end Alembic commands ###
